linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - depguard
    - exhaustive
    - exhaustivestruct # deprecated
    - exhaustruct
    - gochecknoinits
    - gochecknoglobals
    - godox
    - golint # deprecated
    - gomnd # deprecated
    - interfacer # deprecated
    - ireturn
    - maligned # deprecated
    - mnd
    - nilnil
    - nosnakecase # deprecated
    - nlreturn
    - paralleltest
    - scopelint # deprecated
    - structcheck # deprecated
    - varnamelen
    - varcheck # deprecated
    - wrapcheck
    - wsl

linters-settings:
  gomodguard:
    blocked:
      modules:
        - encoding/json:
            recommendations:
              - github.com/goccy/go-json
        - github.com/pkg/errors:
            recommendations:
              - errors
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  nolintlint:
    require-specific: true

issues:
  include:
    - EXC0013
    - EXC0014
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - cyclop
        - err113
        - forcetypeassert
        - funlen
        - goconst
        - gosec
    - path: ((.+)_test.go|internal/test/(.+))
      linters: [govet]
      text: '^fieldalignment:'
    - path: ((.+)_test.go|internal/test/(.+))
      linters: [revive]
      text: '^unused-parameter:'
    - linters: [govet]
      text: '^shadow: declaration of "err" shadows declaration'
