version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - mnd
    - nilnil
    - nlreturn
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gomodguard:
      blocked:
        modules:
          - encoding/json:
              recommendations: [github.com/goccy/go-json]
          - github.com/pkg/errors:
              recommendations: [errors]
    govet:
      enable-all: true
    nolintlint:
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
    rules:
      - linters:
          - cyclop
          - err113
          - forcetypeassert
          - funlen
          - goconst
          - gosec
        path: (.+)_test.go
      - linters: [govet]
        path: ((.+)_test.go|internal/test/(.+))
        text: '^fieldalignment:'
      - linters: [govet]
        text: '^shadow: declaration of "err" shadows declaration'
      - linters: [revive]
        path: ((.+)_test.go|internal/test/(.+))
        text: '^unused-parameter:'
      - linters: [revive]
        text: '^(exported|package-comments): .*$'

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
