linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustive
    - exhaustivestruct # deprecated
    - exhaustruct
    - gochecknoinits
    - gochecknoglobals
    - godox
    - golint # deprecated
    - gomnd
    - interfacer # deprecated
    - ireturn
    - maligned # deprecated
    - nosnakecase # deprecated
    - nlreturn
    - paralleltest
    - scopelint # deprecated
    - structcheck # deprecated
    - varnamelen
    - varcheck # deprecated
    - wrapcheck
    - wsl

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages:
      - encoding/json
      - github.com/pkg/errors
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  nolintlint:
    require-specific: true

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - cyclop
        - forcetypeassert
        - funlen
        - goconst
        - goerr113
        - gosec
    - path: ((.+)_test.go|internal/test/(.+))
      linters: [govet]
      text: '^fieldalignment:'
    - linters: [govet]
      text: '^shadow: declaration of "err" shadows declaration'
