linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - godox
    - golint # deprecated
    - gomnd
    - ifshort # false positives - deprecated
    - interfacer # deprecated
    - ireturn
    - maligned # deprecated
    - nosnakecase # deprecated
    - nlreturn
    - paralleltest
    - scopelint # deprecated
    - structcheck # deprecated
    - testpackage
    - varnamelen
    - varcheck # deprecated
    - wrapcheck
    - wsl

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages:
      - encoding/json
      - github.com/pkg/errors
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/optimusmine/optimusmine)
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  nolintlint:
    allow-leading-space: false
    require-specific: true

issues:
  fix: true
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - errcheck
        - funlen
        - goerr113
        - gosec
    - path: (.+)_test.go
      linters: [govet]
      text: '^fieldalignment:'
    - linters: [govet]
      text: '^shadow: declaration of "err" shadows declaration'
