name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: go
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          bootstrap-sha: 8d7d992a2e4fae93c6e8eb5ab4070d7aefeb737e
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
