name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - go.mod
      - go.sum

  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - run: go test ./... -coverprofile coverage.out

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 66c0ba0b21c425efdcad846946111d21c0dd3b61bdffe68234d9fa09bb20c459
        with:
          coverageLocations: ${{github.workspace}}/coverage.out:gocov
          prefix: github.com/abemedia/go-don

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: golangci-lint.cache-${{ hashFiles('**/go.sum') }}
          restore-keys: golangci-lint.cache-

      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
      - run: golangci-lint run

  # Not supported with Go 1.18
  #     - uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.44
